services:

  backend:
    build: .
    env_file:
      - .env
    environment:
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PWD: ${ADMIN_PWD}
    ports:
      - "9898:3000"
    depends_on:
      - db

  db:
    image: postgres:15

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpwd
      POSTGRES_DB: gestion_locative
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
