services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    env_file:
      - .env
    environment:
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      OWNER_USERNAME: ${OWNER_USERNAME}
      OWNER_EMAIL: ${OWNER_EMAIL}
      OWNER_PWD: ${OWNER_PWD}
      TENANT_USERNAME: ${TENANT_USERNAME}
      TENANT_EMAIL: ${TENANT_EMAIL}
    ports:
      - "9898:3000"
    depends_on:
      - db

  db:
    image: postgres:15

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpwd
      POSTGRES_DB: gestion_locative
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
